

services:
  app:
    build: .
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mysql-server
    environment:
      - FLASK_ENV=development
      - DB_HOST=mysql-server
      - DB_USER=internuser
      - DB_PASSWORD=internpass
      - DB_NAME=internshala_db
    volumes:
      - .:/app

  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: internshala_db
      MYSQL_USER: internuser
      MYSQL_PASSWORD: internpass
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
