"""empty message

Revision ID: 0821fd66593b
Revises: 745f1dd5c11f
Create Date: 2025-04-19 13:50:44.105777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0821fd66593b'
down_revision = '745f1dd5c11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('location')
        batch_op.drop_column('company')
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('company', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('posted_at')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###
