"""empty message

Revision ID: 745f1dd5c11f
Revises: 7cae8dabc21f
Create Date: 2025-04-19 13:48:01.866112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '745f1dd5c11f'
down_revision = '7cae8dabc21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_index('username')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
