"""empty message

Revision ID: 89990be1cdb1
Revises: 7e867717b2d9
Create Date: 2025-04-19 13:55:26.840978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89990be1cdb1'
down_revision = '7e867717b2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
